import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useState } from "react"

import 'bootstrap/dist/css/bootstrap.min.css';
import Button from 'react-bootstrap/Button';
import Container from 'react-bootstrap/Container';
import Form from 'react-bootstrap/Form';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import NavDropdown from 'react-bootstrap/NavDropdown';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [formData, setFormData] = useState({
    name: ""
  })
  const handleInput = (e) => {
    const fieldName = e.target.name;
    const fieldValue = e.target.value;
  
    setFormData((prevState) => ({
      ...prevState,
      [fieldName]: fieldValue
    }));
  }
  const universityName = formData.name
  const handleClick = () => {
    const newURL = `http://localhost:3000/${universityName}`;

    window.history.pushState(null, '', newURL);
    fetch(`http://universities.hipolabs.com/search?name=${universityName}&country=Brazil`)
    .then(response => response.text())
    .then(text => console.log(text))
};
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar expand="lg" className="bg-body-tertiary">
      <Container fluid>
        <Navbar.Brand href="#">University Search</Navbar.Brand>
        <Navbar.Toggle aria-controls="navbarScroll" />
        <Navbar.Collapse id="navbarScroll">
          <Nav
            className="me-auto my-2 my-lg-0"
            style={{ maxHeight: '100px' }}
            navbarScroll
          >
            <Form className="d-flex">
            <Form.Control
              type="search"
              placeholder="Search a University"
              name="name"
              className="me-2"
              aria-label="Search"
              onChange={handleInput}
            />
            <Button variant="outline-success" onClick={handleClick}>Search</Button>
          </Form>
          </Nav>
        </Navbar.Collapse>
      </Container>
    </Navbar>
    <div>
    <label>University Name: </label>
      {universityName}
    </div>
    </>
  )
}
